### ISSUE TITLE
Documentation on running a translator is unclear

### ISSUE THREAD

**Issue by nrdxp** [nix-community/dream2nix#145]
## Issue
I don't understand what I am meant to do from this line alone:
https://github.com/nix-community/dream2nix/blob/main/docs/contributors-guide.md?plain=1#L43

This makes it seem like there is supposed to be some sort of runnable flake app but these are the only apps I see being exported here:
```
│   │   ├───contribute: app
│   │   ├───format: app
│   │   ├───install: app
│   │   ├───tests-all: app
│   │   ├───tests-examples: app
│   │   └───tests-unit: app
```

## Context
As mentioned https://github.com/zaninime/sbt-derivation/issues/5#issuecomment-1124181516, I have a viable path forward for generating functional lock files for SBT based Scala projects (which so far doesn't exist in Nix), and I would very much like to implement a translator and builder here for it, but I am stuck not even understanding how I can run my in progress translator.

**Comment by nrdxp** [comment]
okay after some initial investigation I found this commit:
489f1ab2c779615f84211bc174db47b266a9c638

Which seems to have removed the cli for whatever reason. But there is no explanation in the commit. If the process has changed it would be very nice to update the docs regardless.

**Comment by yusdacra** [comment]
If you are trying to test a translator, you can add sources to translate like [this](https://github.com/nix-community/dream2nix/blob/main/src/translators/rust/pure/cargo-lock/default.nix#L7-L16) to your translator.

Otherwise you could also start a `nix repl`, `:lf <path-to-dream2nix>` and then you can access your translator using `translator = lib.${builtins.currentSystem}.translators.translators.scala.all.<translator-name>` then using the `translator.translate` function. You can pass an attribute set with a `source` specified (and a `project`).

This is all assuming it's a pure translator though (which seems like what you are doing).

**Comment by nrdxp** [comment]
Thank you, but unfortunately it is not a pure translator, I need to call SBT so it can fetch the Scala dependencies once, in order to be able to build the lock file.

**Comment by yusdacra** [comment]
Ah, I see. Then I think an easier way might be to implement a discoverer for Scala, and then just use `dream2nix` on a test repo (the [python discoverer](https://github.com/nix-community/dream2nix/blob/main/src/discoverers/python/default.nix) is simple, so you could just modify that.). You could also do the second way I mentioned, but instead of `.translate`, you could build the `.translateBin` derivation, and use  the resulting script, passing a file path containing a JSON object with `source` and `outputFile` attributes, provided your translator uses those.

**Comment by DavHau** [comment]
In the mean time the contributors docs have been revamped and there is no mention of the cli app anymore.

Anyhow, the docs on writing an impure translator can still be improved, I guess.
