### ISSUE TITLE
docs: add fetchers section

### ISSUE THREAD

**Issue by tinybeachthor** [nix-community/dream2nix#266]
Add documentation section on available source fetchers.

**Comment by DavHau** [comment]
This section should go under `contributing`

**Comment by tinybeachthor** [comment]
I was thinking under `Concepts` 
since `Translators` and `Indexers` are already there, 
would make sense to also add `Fetchers` and `Updaters`.

**Comment by tinybeachthor** [comment]
@DavHau 

How are [updaters](https://github.com/nix-community/dream2nix/blob/667d639c94f08b28378a0d011586ae95e0318ce9/src/updaters/updaters.nix) used atm? I can't quite figure it out.

**Comment by DavHau** [comment]
> since `Translators` and `Indexers` are already there,
> would make sense to also add `Fetchers` and `Updaters`.

Sounds good



> How are [updaters](https://github.com/nix-community/dream2nix/blob/667d639c94f08b28378a0d011586ae95e0318ce9/src/updaters/updaters.nix) used atm? I can't quite figure it out.

Actually it's stale code as of now. There was a dream2nix CLI app which has been deprecated in favor of the declarative flakes approach. The app supported a package update command, that used the updaters. Basically to automatically generate something equivalent to nixpkgs updateScript.

The reason I did not remove the code is because I still have long term plans to re-introduce that feature. We could put a short notice in the readme that this this code will help to generate update-scripts in the future.
