### ISSUE TITLE
Hercules CI doesn't build PRs from external projects

### ISSUE THREAD

**Issue by phaer** [nix-community/dream2nix#626]
...but those checks are expected by github, so merging is blocked.

See e.g. https://github.com/nix-community/dream2nix/pull/620 which never triggered a Hercules CI build according to https://hercules-ci.com/github/nix-community/dream2nix but waits for one since I have approved the checks to run.
 
I have permission to allow the checks, but not to check merge queue and ci settings, so we'll need at least @DavHau. Might be a good idea to ask roberth and/or mic92 about it if we are stuck? Not pinging them until clarified :)

**Comment by DavHau** [comment]
I guess we have to migrate away from hercules. It doesn't seem to work with community contributions.
It won't submit to the merge queue until the checks have passed, but they cannot because hercules blocks.
If I remove the hercules checks from being required, it submits to the queue, but then it also doesn't execute the checks in the queue anymore.

Even if we could make the queue work and execute the checks there, it's still very suboptimal UX. Users should get quick feedback for failing builds on every commit, not just when the PR is submitted to the queue.
Therefore, if that is not possible it doesn't make sense in my opinion to use hercules.

**Comment by phaer** [comment]
Sound's good to me, but do we have an alternative ready? Back to Github Actions? Trying Garnix? Others?

> Even if we could make the queue work and execute the checks there, it's still very suboptimal UX. 

Totally agree, getting rid of that would be great :)

**Comment by DavHau** [comment]
opened https://github.com/hercules-ci/support/issues/70

**Comment by zowoq** [comment]
> Even if we could make the queue work and execute the checks there, it's still very suboptimal UX.

I agree the the UX isn't great but if you'd like an interim solution something like https://github.com/nix-community/infra/pull/793 should work.

We've also talked a little about deploying `buildbot` which would support external PRs but I couldn't say when it would be available.

**Comment by phaer** [comment]
Fixed with the switch to buildbot
