### ISSUE TITLE
packaging ripgrep: not all packages build

### ISSUE THREAD

**Issue by DavHau** [nix-community/dream2nix#91]
using the following `flake.nix`:
```nix
{
  inputs.dream2nix.url = "github:nix-community/dream2nix";
  inputs.src = { flake = false; url = "github:BurntSushi/ripgrep/13.0.0"; };

  outputs = { self, dream2nix, src, }@inputs:
    let
      dream2nix = inputs.dream2nix.lib.init {
        systems = [ "x86_64-linux" ];
        config.projectRoot = ./. ;
      };
    in dream2nix.makeFlakeOutputs {
      source = src;
    };
}
```

...only the ripgrep package builds. All other packages fail with various errors all related to not finding the `Cargo.toml` file.

example:
```
> nix build .#grep
error: builder for '/nix/store/pp7aqc1qnw6lzbvz5ja92230z5fhflji-grep-0.2.8.drv' failed with exit code 101;
       last 10 log lines:
       >   failed to load source for dependency `grep-cli`
       >
       > Caused by:
       >   Unable to update /build/cli
       >
       > Caused by:
       >   failed to read `/build/cli/Cargo.toml`
       >
       > Caused by:
       >   No such file or directory (os error 2)
```

@yusdacra

**Comment by yusdacra** [comment]
I think this is because dream2nix uses the path dependency source, not the workspace source, which means other path dependencies won't be available. It also means that `cargo` won't be able to access the `Cargo.lock`, so even if a path dep had no other path deps, it won't build because of that. Adding a `getSourceRoot` function like described in #83 would fix this.

**Comment by yusdacra** [comment]
I fixed this on #83.

**Comment by yusdacra** [comment]
This should be fixed by #83 being merged.

**Comment by DavHau** [comment]
OK, I checked again and all packages build now. Though all of which I tried don't produce any output (empty ./result).
If I switch to the `crane builder`, all packages result in `./result/bin/rg`.

**Comment by DavHau** [comment]
I guess these are all library packages. Does it even make sense to export them? Maybe we should not.

**Comment by yusdacra** [comment]
They are library packages, so it may not make sense to export them, unless if the user specifically specifies it to be a dynamic library or whatever.

Though IMO this should be left up to the user, so they can just modify the `postInstall` hook to add anything else they want. They should also be able to filter these packages from the output. Maybe it could be useful to add some arguments to `makeFlakeOutputs` for this. Eg. `exposePackages` that takes a list of strings and makes dream2nix only expose the specified packages.

The crane behaviour sounds a bit weird, it's not supposed to build ripgrep on the library packages. I think that is due to `crane` passing the `--workspace` flag by default. Will see about overriding the commands for the main derivation so that it is not passed.

**Comment by DavHau** [comment]
> Though IMO this should be left up to the user, so they can just modify the postInstall hook to add anything else they want.

I'm not quite sure yet about how a use case for this would look like. Let's say someone would want to make a package that should depend upon libraries built with rust, then they would declare the library outputs coming from dream2nix as an input to their derivation, right?

But the result of our build is currently empty. If we want to support that use case then our derivation should have a `result/lib` a `lib` output that can be built.

Right now I feel we should probably either provide these `lib` outputs or not export these derivations.

**Comment by yusdacra** [comment]
`crane` will install lib outputs, if there are any. I'm not sure if `buildRustPackage` does that. These packages don't really have any lib outputs, so nothing is installed.

For example `nix-cargo-integration` works around these by just disabling all outputs for crates default, and makes you add a metadata value to the package `Cargo.toml` for enabling outputs for that crate.

But for `dream2nix` I would say it's better if all packages are outputted by default, for exposure, and then the user should be able to disable them. It seems rather opinionated to not expose packages because of this, which IMO is better expressed with higher abstraction layers. For example, there could be a use case where a crate has no outputs, but it's `build.rs` will build something and put it in `target`. This wouldn't be installed by `crane` or `buildRustPackage`. I think not exposing that would make the user more confused, because first they'd need to expose that, and then find out their output wasn't installed, as opposed to just finding out their output wasn't installed.
